//! `cargo xtask gen-tables --pokered <dir>`: regenerate the static data
//! tables in `crates/pksave/src/gen1/data/generated/` from a pret/pokered
//! checkout, by plain text parsing of its .asm files.
//!
//! Parsing is deliberately strict: any line that does not match the expected
//! shape panics with file+line context rather than silently producing wrong
//! tables.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use crate::charmap::Charmap;
use crate::pins;

pub fn run(pokered: &Path) {
    assert!(
        pokered.join("constants/pokemon_constants.asm").is_file(),
        "{} does not look like a pokered checkout",
        pokered.display()
    );
    let out_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../pksave/src/gen1/data/generated");
    fs::create_dir_all(&out_dir).unwrap_or_else(|e| panic!("create {}: {e}", out_dir.display()));

    let charmap = Charmap::load(&pokered.join("constants/charmap.asm"));

    write_generated(&out_dir, "species.rs", gen_species(pokered, &charmap));
    write_generated(&out_dir, "moves.rs", gen_moves(pokered, &charmap));
    write_generated(&out_dir, "items.rs", gen_items(pokered, &charmap));
    write_generated(&out_dir, "types.rs", gen_types(pokered, &charmap));
    write_generated(&out_dir, "events.rs", gen_events(pokered));
    write_generated(&out_dir, "maps.rs", gen_maps(pokered));

    println!("generated tables in {}", out_dir.display());
}

fn write_generated(dir: &Path, name: &str, body: String) {
    let path = dir.join(name);
    let header = format!(
        "//! Generated by `cargo xtask gen-tables` from pret/pokered @ {} — do not edit.\n",
        pins::POKERED_SHA
    );
    fs::write(&path, header + &body).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
    // Keep the checked-in files identical whether they come fresh from
    // gen-tables or have been through `cargo fmt --all`.
    let status = std::process::Command::new("rustfmt")
        .arg("--edition=2021")
        .arg(&path)
        .status()
        .unwrap_or_else(|e| panic!("run rustfmt on {}: {e}", path.display()));
    assert!(status.success(), "rustfmt failed on {}", path.display());
    println!("wrote {name}");
}

// ---------------------------------------------------------------------------
// Low-level .asm line helpers
// ---------------------------------------------------------------------------

struct AsmFile {
    path: PathBuf,
    lines: Vec<String>,
}

impl AsmFile {
    fn load(pokered: &Path, rel: &str) -> AsmFile {
        let path = pokered.join(rel);
        let text =
            fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        AsmFile {
            path,
            lines: text.lines().map(str::to_string).collect(),
        }
    }

    fn ctx(&self, lineno: usize) -> String {
        format!("{}:{}", self.path.display(), lineno + 1)
    }

    /// Iterate `(lineno, code)` with comments stripped and blanks skipped.
    fn code_lines(&self) -> impl Iterator<Item = (usize, String)> + '_ {
        self.lines.iter().enumerate().filter_map(|(n, line)| {
            let code = strip_comment(line).trim().to_string();
            (!code.is_empty()).then_some((n, code))
        })
    }
}

/// Strip a `;` comment, ignoring semicolons inside double-quoted strings.
fn strip_comment(line: &str) -> &str {
    let mut in_string = false;
    for (i, c) in line.char_indices() {
        match c {
            '"' => in_string = !in_string,
            ';' if !in_string => return &line[..i],
            _ => {}
        }
    }
    line
}

/// Parse an integer literal: `$1F` (hex), `%101` (binary), or decimal.
fn parse_num(tok: &str, ctx: &str) -> i64 {
    let tok = tok.trim();
    let parsed = if let Some(hex) = tok.strip_prefix('$') {
        i64::from_str_radix(hex, 16)
    } else if let Some(bin) = tok.strip_prefix('%') {
        i64::from_str_radix(bin, 2)
    } else {
        tok.parse()
    };
    parsed.unwrap_or_else(|_| panic!("{ctx}: expected number, got {tok:?}"))
}

/// Evaluate `NUM (('+'|'-') NUM)*`, e.g. `$F0 - 2` in const_next.
fn eval_expr(expr: &str, ctx: &str) -> i64 {
    let mut tokens = expr.split_whitespace();
    let first = tokens
        .next()
        .unwrap_or_else(|| panic!("{ctx}: empty const expression"));
    let mut value = parse_num(first, ctx);
    while let Some(op) = tokens.next() {
        let rhs = tokens
            .next()
            .unwrap_or_else(|| panic!("{ctx}: dangling operator in {expr:?}"));
        match op {
            "+" => value += parse_num(rhs, ctx),
            "-" => value -= parse_num(rhs, ctx),
            _ => panic!("{ctx}: unsupported operator {op:?} in {expr:?}"),
        }
    }
    value
}

/// Extract the string from a `"..."` literal starting at `s`.
fn quoted(s: &str, ctx: &str) -> String {
    let s = s.trim();
    let inner = s
        .strip_prefix('"')
        .unwrap_or_else(|| panic!("{ctx}: expected quoted string, got {s:?}"));
    let end = inner
        .find('"')
        .unwrap_or_else(|| panic!("{ctx}: unterminated string in {s:?}"));
    inner[..end].to_string()
}

// ---------------------------------------------------------------------------
// RGBDS `const_def`/`const`/`const_skip`/`const_next` scanner
// ---------------------------------------------------------------------------

struct ConstScan {
    /// `(value, name)` in declaration order.
    items: Vec<(i64, String)>,
    /// `const_value` at the stop line.
    final_value: i64,
}

/// Scan a constants file. `map_const` (from `constants/map_constants.asm`) is
/// treated as a plain `const` of its first argument. Scanning starts at the
/// first `const_def` (so `const \1` lines inside MACRO bodies are ignored)
/// and ends when `stop` matches (the stop line is not processed).
fn scan_consts(file: &AsmFile, stop: &dyn Fn(&str) -> bool) -> ConstScan {
    let mut items: Vec<(i64, String)> = Vec::new();
    let mut value: i64 = 0;
    let mut started = false;
    let mut stopped = false;

    for (lineno, code) in file.code_lines() {
        let ctx = || file.ctx(lineno);
        if stop(&code) {
            stopped = true;
            break;
        }
        let (word, rest) = match code.split_once(char::is_whitespace) {
            Some((w, r)) => (w, r.trim()),
            None => (code.as_str(), ""),
        };
        if word == "const_def" {
            started = true;
            value = if rest.is_empty() {
                0
            } else {
                eval_expr(rest, &ctx())
            };
            continue;
        }
        if !started {
            continue;
        }
        match word {
            "const" | "map_const" => {
                let name = rest
                    .split([',', ' ', '\t'])
                    .next()
                    .filter(|n| !n.is_empty())
                    .unwrap_or_else(|| panic!("{}: const without a name", ctx()));
                assert!(
                    name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'),
                    "{}: unexpected const name {name:?} (macro body?)",
                    ctx()
                );
                items.push((value, name.to_string()));
                value += 1;
            }
            "const_skip" => {
                value += if rest.is_empty() {
                    1
                } else {
                    eval_expr(rest, &ctx())
                };
            }
            "const_next" => {
                let next = eval_expr(rest, &ctx());
                assert!(next >= value, "{}: const_next goes backwards", ctx());
                value = next;
            }
            "end_indoor_group" => {} // map_constants bookkeeping, no id consumed
            _ => {}                  // DEF/ASSERT/labels/etc.
        }
    }
    assert!(
        stopped,
        "{}: never reached expected end marker",
        file.path.display()
    );
    ConstScan {
        items,
        final_value: value,
    }
}

fn const_map(scan: &ConstScan) -> BTreeMap<String, i64> {
    scan.items.iter().map(|(v, n)| (n.clone(), *v)).collect()
}

// ---------------------------------------------------------------------------
// species.rs
// ---------------------------------------------------------------------------

fn gen_species(pokered: &Path, charmap: &Charmap) -> String {
    // Internal index -> constant name ($00 NO_MON .. $BE VICTREEBEL, 39 gaps).
    let mons_file = AsmFile::load(pokered, "constants/pokemon_constants.asm");
    let mons = scan_consts(&mons_file, &|l| l.starts_with("DEF NUM_POKEMON_INDEXES"));
    let num_indexes = mons.final_value - 1;
    assert_eq!(num_indexes, 190, "NUM_POKEMON_INDEXES changed");
    assert_eq!(mons.items[0], (0, "NO_MON".to_string()));
    let internal_by_index: BTreeMap<i64, String> =
        mons.items.iter().map(|(v, n)| (*v, n.clone())).collect();

    // DEX_* constant -> dex number (1..=151).
    let dex_file = AsmFile::load(pokered, "constants/pokedex_constants.asm");
    let dex = scan_consts(&dex_file, &|l| l.starts_with("DEF NUM_POKEMON"));
    assert_eq!(dex.final_value - 1, 151, "NUM_POKEMON changed");
    let dex_values = const_map(&dex);

    // PokedexOrder: one db per internal index 1..=190.
    let order_file = AsmFile::load(pokered, "data/pokemon/dex_order.asm");
    let mut order: Vec<u8> = Vec::new();
    for (lineno, code) in order_file.code_lines() {
        let ctx = || order_file.ctx(lineno);
        if code.starts_with("assert_table_length") {
            break;
        }
        let Some(entry) = code.strip_prefix("db ") else {
            continue; // label / table_width
        };
        let entry = entry.trim();
        if entry == "0" {
            order.push(0);
        } else {
            let value = *dex_values
                .get(entry)
                .unwrap_or_else(|| panic!("{}: unknown dex constant {entry:?}", ctx()));
            order.push(u8::try_from(value).expect("dex number fits in u8"));
        }
    }
    assert_eq!(order.len(), 190, "PokedexOrder length changed");

    // Cross-check PokedexOrder against the internal constant list: gaps in
    // one must be gaps in the other, and names must correspond where the
    // internal mon has a real dex entry.
    let mut index_to_dex = [0u8; 256];
    for (i, &dexno) in order.iter().enumerate() {
        let index = i as i64 + 1;
        index_to_dex[index as usize] = dexno;
        match (internal_by_index.get(&index), dexno) {
            (None, 0) => {}
            (None, d) => panic!("internal index ${index:02X} is const_skip but has dex {d}"),
            (Some(_), 0) => {} // named glitch entries (FOSSIL_*, MON_GHOST) have dex 0
            (Some(name), d) => {
                let expected = format!("DEX_{name}");
                assert_eq!(
                    dex_values.get(&expected).copied(),
                    Some(d as i64),
                    "internal {name} (index ${index:02X}) does not map to {expected}"
                );
            }
        }
    }
    let nonzero = index_to_dex.iter().filter(|&&d| d != 0).count();
    assert_eq!(nonzero, 151, "expected 151 valid species");

    let mut dex_to_index = [0u8; 152];
    for (index, &dexno) in index_to_dex.iter().enumerate() {
        if dexno != 0 {
            assert_eq!(dex_to_index[dexno as usize], 0, "dex {dexno} mapped twice");
            dex_to_index[dexno as usize] = index as u8;
        }
    }
    assert!(
        dex_to_index[1..].iter().all(|&i| i != 0),
        "dex map not surjective"
    );

    // MonsterNames: 190 dname entries in internal-index order.
    let names_file = AsmFile::load(pokered, "data/pokemon/names.asm");
    let mut internal_names: Vec<String> = Vec::new();
    for (lineno, code) in names_file.code_lines() {
        if code.starts_with("assert_table_length") {
            break;
        }
        if let Some(rest) = code.strip_prefix("dname ") {
            internal_names.push(quoted(rest, &names_file.ctx(lineno)));
        }
    }
    assert_eq!(internal_names.len(), 190, "MonsterNames length changed");

    let mut species_names = vec![String::new(); 152];
    for dexno in 1..=151usize {
        let index = dex_to_index[dexno] as usize;
        let raw = &internal_names[index - 1];
        species_names[dexno] =
            charmap.normalize(raw, &format!("{} (dex {dexno})", names_file.path.display()));
    }

    let base_stats = parse_base_stats(pokered, &dex_values);

    // ---- emit ----
    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(w, "//! Species tables, indexed as documented per item.");
    let _ = writeln!(w);
    let _ = writeln!(w, "use crate::gen1::data::BaseStats;");
    let _ = writeln!(w);
    let _ = writeln!(w, "/// Internal species index -> National Dex number");
    let _ = writeln!(
        w,
        "/// (0 for NO_MON, MissingNo and other invalid indexes)."
    );
    emit_u8_array(w, "INDEX_TO_DEX", &index_to_dex);
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "/// National Dex number (1-151) -> internal species index; `[0]` unused."
    );
    emit_u8_array(w, "DEX_TO_INDEX", &dex_to_index);
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "/// English species names indexed by National Dex number; `[0]` unused."
    );
    emit_str_array(w, "SPECIES_NAMES", &species_names);
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "/// Base stats indexed by National Dex number; `[0]` unused (all zero)."
    );
    let _ = writeln!(w, "pub const BASE_STATS: [BaseStats; 152] = [");
    let zero = [0u8; 10];
    let _ = writeln!(w, "    {}", base_stats_literal(&zero));
    for (dexno, stats) in base_stats.iter().enumerate() {
        let _ = writeln!(w, "    // {} {}", dexno + 1, species_names[dexno + 1]);
        let _ = writeln!(w, "    {}", base_stats_literal(stats));
    }
    let _ = writeln!(w, "];");
    out
}

/// Parse all 151 base stats files (dex order; Mew lives apart) into raw
/// `[hp, atk, def, spd, spc, type1, type2, catch, exp, growth]` rows.
fn parse_base_stats(pokered: &Path, dex_values: &BTreeMap<String, i64>) -> Vec<[u8; 10]> {
    let type_values = const_map(&scan_consts(
        &AsmFile::load(pokered, "constants/type_constants.asm"),
        &|l| l.starts_with("DEF NUM_TYPES"),
    ));
    let growth_values = parse_growth_constants(pokered);

    // Include order from base_stats.asm (dex 1..=150) ...
    let list = AsmFile::load(pokered, "data/pokemon/base_stats.asm");
    let mut files: Vec<String> = Vec::new();
    for (lineno, code) in list.code_lines() {
        if let Some(rest) = code.strip_prefix("INCLUDE ") {
            files.push(quoted(rest, &list.ctx(lineno)));
        }
    }
    assert_eq!(files.len(), 150, "base_stats.asm include count changed");
    // ... plus Mew's, included from data/pokemon/mew.asm (dex 151).
    let mew = AsmFile::load(pokered, "data/pokemon/mew.asm");
    let mew_includes: Vec<String> = mew
        .code_lines()
        .filter_map(|(lineno, code)| {
            code.strip_prefix("INCLUDE ")
                .filter(|rest| rest.contains("base_stats"))
                .map(|rest| quoted(rest, &mew.ctx(lineno)))
        })
        .collect();
    assert_eq!(
        mew_includes,
        ["data/pokemon/base_stats/mew.asm"],
        "mew.asm base stats include changed"
    );
    files.extend(mew_includes);

    let mut rows = Vec::new();
    for (i, rel) in files.iter().enumerate() {
        let dexno = i as i64 + 1;
        let file = AsmFile::load(pokered, rel);
        // Collect `db` entries in order; fields are positional (see the
        // commented layout in any base_stats file).
        let mut dbs: Vec<(usize, Vec<String>)> = Vec::new();
        for (lineno, code) in file.code_lines() {
            if let Some(rest) = code.strip_prefix("db ") {
                dbs.push((
                    lineno,
                    rest.split(',').map(|f| f.trim().to_string()).collect(),
                ));
            }
        }
        assert!(
            dbs.len() >= 7,
            "{}: expected at least 7 db lines",
            file.path.display()
        );

        let field = |db: usize, n: usize, want: usize| -> String {
            let (lineno, fields) = &dbs[db];
            assert_eq!(
                fields.len(),
                want,
                "{}: expected {want} comma-separated fields",
                file.ctx(*lineno)
            );
            fields[n].clone()
        };
        let num = |db: usize, n: usize, want: usize| -> u8 {
            let value = parse_num(&field(db, n, want), &file.ctx(dbs[db].0));
            u8::try_from(value).unwrap_or_else(|_| {
                panic!("{}: value {value} out of u8 range", file.ctx(dbs[db].0))
            })
        };

        // db 0: pokedex id — must match this file's position in the list.
        let dex_const = field(0, 0, 1);
        assert_eq!(
            dex_values.get(&dex_const).copied(),
            Some(dexno),
            "{}: dex id {dex_const} does not match include position {dexno}",
            file.path.display()
        );
        // db 1: hp, atk, def, spd, spc
        let stats: Vec<u8> = (0..5).map(|n| num(1, n, 5)).collect();
        // db 2: type1, type2
        let type_of = |n: usize| -> u8 {
            let name = field(2, n, 2);
            let value = *type_values
                .get(&name)
                .unwrap_or_else(|| panic!("{}: unknown type {name:?}", file.ctx(dbs[2].0)));
            u8::try_from(value).expect("type id fits in u8")
        };
        let (type1, type2) = (type_of(0), type_of(1));
        // db 3: catch rate; db 4: base exp yield; db 5: level-1 learnset
        // (skipped); db 6: growth rate.
        let catch_rate = num(3, 0, 1);
        let exp_yield = num(4, 0, 1);
        assert_eq!(
            dbs[5].1.len(),
            4,
            "{}: expected 4 level-1 moves",
            file.ctx(dbs[5].0)
        );
        let growth_name = field(6, 0, 1);
        let growth = *growth_values.get(&growth_name).unwrap_or_else(|| {
            panic!(
                "{}: unknown growth rate {growth_name:?}",
                file.ctx(dbs[6].0)
            )
        });

        rows.push([
            stats[0],
            stats[1],
            stats[2],
            stats[3],
            stats[4],
            type1,
            type2,
            catch_rate,
            exp_yield,
            u8::try_from(growth).expect("growth rate fits in u8"),
        ]);
    }
    rows
}

fn parse_growth_constants(pokered: &Path) -> BTreeMap<String, i64> {
    let file = AsmFile::load(pokered, "constants/pokemon_data_constants.asm");
    let scan = scan_consts(&file, &|l| l.starts_with("DEF NUM_GROWTH_RATES"));
    // The file holds several const blocks; keep only the GROWTH_* one and
    // verify it is the contiguous block ending at NUM_GROWTH_RATES.
    let growth: BTreeMap<String, i64> = scan
        .items
        .iter()
        .filter(|(_, n)| n.starts_with("GROWTH_"))
        .map(|(v, n)| (n.clone(), *v))
        .collect();
    assert_eq!(
        growth.len() as i64,
        scan.final_value,
        "GROWTH_* block not contiguous"
    );
    assert_eq!(growth.get("GROWTH_MEDIUM_FAST"), Some(&0));
    assert_eq!(growth.get("GROWTH_SLOW"), Some(&5));
    growth
}

fn base_stats_literal(row: &[u8; 10]) -> String {
    format!(
        "BaseStats {{ hp: {}, attack: {}, defense: {}, speed: {}, special: {}, \
         type1: {}, type2: {}, catch_rate: {}, exp_yield: {}, growth_rate: {} }},",
        row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9]
    )
}

// ---------------------------------------------------------------------------
// moves.rs
// ---------------------------------------------------------------------------

fn gen_moves(pokered: &Path, charmap: &Charmap) -> String {
    let const_file = AsmFile::load(pokered, "constants/move_constants.asm");
    let consts = scan_consts(&const_file, &|l| l.starts_with("DEF NUM_ATTACKS"));
    assert_eq!(consts.final_value - 1, 165, "NUM_ATTACKS changed");
    assert_eq!(consts.items[0], (0, "NO_MOVE".to_string()));
    assert_eq!(consts.items.len(), 166, "move ids must be dense 0..=165");

    let type_values = const_map(&scan_consts(
        &AsmFile::load(pokered, "constants/type_constants.asm"),
        &|l| l.starts_with("DEF NUM_TYPES"),
    ));

    let names_file = AsmFile::load(pokered, "data/moves/names.asm");
    let names = parse_li_list(&names_file, charmap);
    assert_eq!(names.len(), 165, "MoveNames length changed");

    let moves_file = AsmFile::load(pokered, "data/moves/moves.asm");
    let mut rows: Vec<(u8, u8, u8, u8)> = Vec::new(); // power, type, accuracy, pp
    for (lineno, code) in moves_file.code_lines() {
        let Some(rest) = code.strip_prefix("move ") else {
            continue; // macro definition, table_width, labels
        };
        let ctx = || moves_file.ctx(lineno);
        let fields: Vec<&str> = rest.split(',').map(str::trim).collect();
        assert_eq!(fields.len(), 6, "{}: expected 6 move fields", ctx());
        let expected_const = &consts.items[rows.len() + 1].1;
        assert_eq!(
            fields[0],
            expected_const,
            "{}: move order diverges from constants/move_constants.asm",
            ctx()
        );
        let power = parse_num(fields[2], &ctx());
        let type_ = *type_values
            .get(fields[3])
            .unwrap_or_else(|| panic!("{}: unknown type {:?}", ctx(), fields[3]));
        let percent = parse_num(fields[4], &ctx());
        assert!(
            (0..=100).contains(&percent),
            "{}: accuracy out of range",
            ctx()
        );
        let accuracy = percent * 255 / 100; // the ROM stores `\5 percent`
        let pp = parse_num(fields[5], &ctx());
        assert!((0..=40).contains(&pp), "{}: PP out of range", ctx());
        rows.push((
            u8::try_from(power).unwrap_or_else(|_| panic!("{}: power out of range", ctx())),
            u8::try_from(type_).expect("type id fits in u8"),
            u8::try_from(accuracy).expect("accuracy fits in u8"),
            u8::try_from(pp).expect("pp fits in u8"),
        ));
    }
    assert_eq!(rows.len(), 165, "Moves table length changed");

    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(
        w,
        "//! Move table indexed by move id (0 = none, 1-165 real moves)."
    );
    let _ = writeln!(w);
    let _ = writeln!(w, "use crate::gen1::data::MoveInfo;");
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "/// `accuracy` is the raw ROM byte: `percent * 255 / 100` (100% = 255)."
    );
    let _ = writeln!(w, "pub const MOVES: [MoveInfo; 166] = [");
    let _ = writeln!(
        w,
        "    MoveInfo {{ name: \"\", power: 0, type_: 0, accuracy: 0, pp: 0 }},"
    );
    for (i, (power, type_, accuracy, pp)) in rows.iter().enumerate() {
        let _ = writeln!(
            w,
            "    MoveInfo {{ name: {:?}, power: {power}, type_: {type_}, \
             accuracy: {accuracy}, pp: {pp} }},",
            names[i]
        );
    }
    let _ = writeln!(w, "];");
    out
}

/// Parse a `list_start` / `li "NAME"` list, normalizing each entry through
/// the Gen 1 charmap.
fn parse_li_list(file: &AsmFile, charmap: &Charmap) -> Vec<String> {
    let mut names = Vec::new();
    for (lineno, code) in file.code_lines() {
        // assert_list_length may occur mid-list (e.g. after the regular
        // items, before the elevator floors) — it is not a terminator.
        if let Some(rest) = code.strip_prefix("li ") {
            let ctx = file.ctx(lineno);
            names.push(charmap.normalize(&quoted(rest, &ctx), &ctx));
        }
    }
    names
}

// ---------------------------------------------------------------------------
// items.rs
// ---------------------------------------------------------------------------

fn gen_items(pokered: &Path, charmap: &Charmap) -> String {
    // Regular item + elevator-floor ids: constants up to the `const_next $C4`
    // jump that starts the HM/TM range.
    let const_file = AsmFile::load(pokered, "constants/item_constants.asm");
    let consts = scan_consts(&const_file, &|l| l.starts_with("const_next"));
    assert_eq!(consts.items[0], (0, "NO_ITEM".to_string()));
    assert_eq!(consts.items.len(), 0x62, "item constant count changed");
    assert!(
        consts
            .items
            .iter()
            .enumerate()
            .all(|(i, (v, _))| *v == i as i64),
        "item ids must be dense"
    );

    let names_file = AsmFile::load(pokered, "data/items/names.asm");
    let names = parse_li_list(&names_file, charmap);
    assert_eq!(
        names.len(),
        consts.items.len() - 1,
        "ItemNames length does not match item constants"
    );

    let mut item_names = vec![String::new(); 256];
    item_names[1..=0x61].clone_from_slice(&names);
    // HM01-HM05 ($C4-$C8) and TM01-TM55 ($C9-$FF): ItemNames stops before
    // them; the game prints "TMxx"/"HMxx" from the item id (TM55 = $FF is a
    // glitch TM but still renders this way).
    for (id, name) in item_names.iter_mut().enumerate().take(0xC9).skip(0xC4) {
        *name = format!("HM{:02}", id - 0xC3);
    }
    for (id, name) in item_names.iter_mut().enumerate().skip(0xC9) {
        *name = format!("TM{:02}", id - 0xC8);
    }

    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(
        w,
        "//! Item names indexed by item id (\"\" for invalid/glitch ids)."
    );
    let _ = writeln!(w, "//!");
    let _ = writeln!(
        w,
        "//! Ids $54-$61 are the elevator floor pseudo-items; $C4-$C8 are"
    );
    let _ = writeln!(
        w,
        "//! HM01-HM05 and $C9-$FF are TM01-TM55, named the way the game"
    );
    let _ = writeln!(w, "//! renders them.");
    let _ = writeln!(w);
    emit_str_array(w, "ITEM_NAMES", &item_names);
    out
}

// ---------------------------------------------------------------------------
// types.rs
// ---------------------------------------------------------------------------

fn gen_types(pokered: &Path, charmap: &Charmap) -> String {
    let const_file = AsmFile::load(pokered, "constants/type_constants.asm");
    let consts = scan_consts(&const_file, &|l| l.starts_with("DEF NUM_TYPES"));
    let num_types = consts.final_value;
    assert_eq!(num_types, 0x1B, "NUM_TYPES changed");

    // data/types/names.asm: a `dw .Label` per declared type constant, in the
    // same order (the REPT block fills the unused-id gap), then `.Label: db`
    // strings.
    let names_file = AsmFile::load(pokered, "data/types/names.asm");
    let mut dw_labels: Vec<String> = Vec::new();
    let mut strings: BTreeMap<String, String> = BTreeMap::new();
    let mut in_rept = false;
    for (lineno, code) in names_file.code_lines() {
        let ctx = || names_file.ctx(lineno);
        if code.starts_with("REPT") {
            in_rept = true;
        } else if code.starts_with("ENDR") {
            in_rept = false;
        } else if let Some(rest) = code.strip_prefix("dw ") {
            if in_rept {
                continue; // gap filler (points at .Normal)
            }
            let label = rest
                .trim()
                .strip_prefix('.')
                .unwrap_or_else(|| panic!("{}: expected local label in dw", ctx()));
            dw_labels.push(label.to_string());
        } else if let Some(label_rest) = code.strip_prefix('.') {
            let (label, rest) = label_rest
                .split_once(':')
                .unwrap_or_else(|| panic!("{}: expected `.Label:`", ctx()));
            let rest = rest.trim();
            let db = rest
                .strip_prefix("db ")
                .unwrap_or_else(|| panic!("{}: expected db string after label", ctx()));
            let raw = quoted(db, &ctx());
            let raw = raw
                .strip_suffix('@')
                .unwrap_or_else(|| panic!("{}: type name missing @ terminator", ctx()));
            strings.insert(label.to_string(), charmap.normalize(raw, &ctx()));
        }
    }
    assert_eq!(
        dw_labels.len(),
        consts.items.len(),
        "type name pointer count does not match type constants"
    );

    let mut type_names = vec![String::new(); num_types as usize];
    for ((id, const_name), label) in consts.items.iter().zip(&dw_labels) {
        let name = strings
            .get(label)
            .unwrap_or_else(|| panic!("no string for type label .{label}"));
        type_names[*id as usize] = name.clone();
        // Sanity: the label should match the constant (PSYCHIC_TYPE -> Psychic).
        let normalized_const = const_name.replace("_TYPE", "").replace('_', "");
        assert!(
            normalized_const.eq_ignore_ascii_case(label),
            "type constant {const_name} paired with unexpected label .{label}"
        );
    }

    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(w, "//! Type names indexed by Gen 1 type id.");
    let _ = writeln!(w, "//!");
    let _ = writeln!(
        w,
        "//! Type ids are sparse: $00-$08 are the physical types, $14-$1A the"
    );
    let _ = writeln!(w, "//! special types, and $09-$13 are unused (\"\").");
    let _ = writeln!(w);
    emit_str_array(w, "TYPE_NAMES", &type_names);
    out
}

// ---------------------------------------------------------------------------
// events.rs
// ---------------------------------------------------------------------------

fn gen_events(pokered: &Path) -> String {
    let file = AsmFile::load(pokered, "constants/event_constants.asm");
    let scan = scan_consts(&file, &|l| l.starts_with("DEF NUM_EVENTS"));
    let num_events = scan.final_value;

    // Pin the shape of the source so silent upstream changes fail generation:
    // 507 named events on sparse bit indexes, NUM_EVENTS = $A00 (wEventFlags
    // is flag_array NUM_EVENTS = 320 bytes).
    assert_eq!(scan.items.len(), 507, "event constant count changed");
    assert_eq!(num_events, 0xA00, "NUM_EVENTS changed");
    let max_bit = scan.items.iter().map(|(v, _)| *v).max().expect("nonempty");
    assert_eq!(max_bit, 2522, "last event bit changed");
    for (bit, name) in &scan.items {
        assert!(
            name.starts_with("EVENT_"),
            "unexpected event constant {name} at bit {bit}"
        );
        assert!(
            (0..num_events).contains(bit),
            "event bit {bit} out of range"
        );
    }

    let mut names = vec![String::new(); num_events as usize];
    for (bit, name) in &scan.items {
        assert!(
            names[*bit as usize].is_empty(),
            "event bit {bit} declared twice"
        );
        names[*bit as usize] = name.clone();
    }

    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(
        w,
        "//! Event flag names indexed by `wEventFlags` bit number."
    );
    let _ = writeln!(w, "//!");
    let _ = writeln!(
        w,
        "//! pokered allocates event bits per map with gaps; unnamed bits"
    );
    let _ = writeln!(
        w,
        "//! are \"\". 507 bits are named; NUM_EVENTS = $A00 = 2560 bits"
    );
    let _ = writeln!(
        w,
        "//! (wEventFlags spans 320 bytes of WRAM, all copied into the save)."
    );
    let _ = writeln!(w);
    emit_str_array_decl(w, "static", "EVENT_FLAG_NAMES", &names);
    out
}

// ---------------------------------------------------------------------------
// maps.rs
// ---------------------------------------------------------------------------

fn gen_maps(pokered: &Path) -> String {
    let file = AsmFile::load(pokered, "constants/map_constants.asm");
    let scan = scan_consts(&file, &|l| l.starts_with("DEF NUM_MAPS"));
    let num_maps = scan.final_value;
    assert_eq!(num_maps, 0xF8, "NUM_MAPS changed");
    assert_eq!(scan.items.len() as i64, num_maps, "map ids must be dense");

    let mut names = vec![String::new(); 256];
    for (id, name) in &scan.items {
        names[*id as usize] = name.clone();
    }

    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(
        w,
        "//! Map constant names indexed by map id (\"\" for unused ids)."
    );
    let _ = writeln!(w);
    emit_str_array(w, "MAP_NAMES", &names);
    out
}

// ---------------------------------------------------------------------------
// Array emission
// ---------------------------------------------------------------------------

fn emit_u8_array(out: &mut String, name: &str, values: &[u8]) {
    let _ = writeln!(out, "pub const {name}: [u8; {}] = [", values.len());
    for chunk in values.chunks(16) {
        let row: Vec<String> = chunk.iter().map(|v| format!("{v:#04X}")).collect();
        let _ = writeln!(out, "    {},", row.join(", "));
    }
    let _ = writeln!(out, "];");
}

fn emit_str_array(out: &mut String, name: &str, values: &[String]) {
    emit_str_array_decl(out, "const", name, values);
}

/// Like [`emit_str_array`] but lets the caller pick `const`/`static`
/// (clippy's `large_const_arrays` wants big tables as `static`).
fn emit_str_array_decl(out: &mut String, decl: &str, name: &str, values: &[String]) {
    let _ = writeln!(out, "pub {decl} {name}: [&str; {}] = [", values.len());
    let mut i = 0;
    while i < values.len() {
        if values[i].is_empty() {
            // Compact runs of empty entries.
            let start = i;
            while i < values.len() && values[i].is_empty() {
                i += 1;
            }
            let row: Vec<&str> = (start..i).map(|_| "\"\"").collect();
            for chunk in row.chunks(16) {
                let _ = writeln!(out, "    {},", chunk.join(", "));
            }
        } else {
            let _ = writeln!(out, "    {:?}, // {i:#04X}", values[i]);
            i += 1;
        }
    }
    let _ = writeln!(out, "];");
}
