//! Tests for the static data tables generated by `cargo xtask gen-tables`
//! from the pinned pret/pokered checkout.
//!
//! Expected values below were cross-checked against the pokered sources
//! (constants/*.asm, data/pokemon/*, data/moves/*, data/items/*).

use pksave::gen1::data::generated::events::EVENT_FLAG_NAMES;
use pksave::gen1::data::generated::items::ITEM_NAMES;
use pksave::gen1::data::generated::maps::MAP_NAMES;
use pksave::gen1::data::generated::moves::MOVES;
use pksave::gen1::data::generated::species::{
    BASE_STATS, DEX_TO_INDEX, INDEX_TO_DEX, SPECIES_NAMES,
};
use pksave::gen1::data::generated::types::TYPE_NAMES;
use pksave::gen1::data::BaseStats;

#[test]
fn index_to_dex_spot_checks() {
    assert_eq!(INDEX_TO_DEX[0x01], 112, "Rhydon");
    assert_eq!(INDEX_TO_DEX[0x99], 1, "Bulbasaur");
    assert_eq!(INDEX_TO_DEX[0xB0], 4, "Charmander");
    assert_eq!(INDEX_TO_DEX[0xB1], 7, "Squirtle");
    assert_eq!(INDEX_TO_DEX[0x15], 151, "Mew");
}

#[test]
fn dex_index_bijectivity() {
    for dex in 1..=151u16 {
        let idx = DEX_TO_INDEX[dex as usize];
        assert_ne!(idx, 0, "dex {dex} has no internal index");
        assert_eq!(
            INDEX_TO_DEX[idx as usize] as u16, dex,
            "round-trip failed for dex {dex} (internal index {idx})"
        );
    }
    assert_eq!(DEX_TO_INDEX[0], 0);

    assert_eq!(INDEX_TO_DEX[0], 0, "index 0 is NO_MON");
    let nonzero = INDEX_TO_DEX[1..=190].iter().filter(|&&d| d != 0).count();
    assert_eq!(nonzero, 151, "exactly 151 valid internal indexes");
    let zero = INDEX_TO_DEX[1..=190].iter().filter(|&&d| d == 0).count();
    assert_eq!(zero, 39, "exactly 39 MissingNo gap indexes");
    assert!(
        INDEX_TO_DEX[191..].iter().all(|&d| d == 0),
        "indexes 191..=255 are invalid"
    );
}

#[test]
fn species_names() {
    assert_eq!(SPECIES_NAMES[0], "");
    assert_eq!(SPECIES_NAMES[1], "BULBASAUR");
    assert_eq!(SPECIES_NAMES[25], "PIKACHU");
    // data/pokemon/names.asm: `dname "MR.MIME"` (no space).
    assert_eq!(SPECIES_NAMES[122], "MR.MIME");
    assert_eq!(SPECIES_NAMES[83], "FARFETCH'D");
    assert_eq!(SPECIES_NAMES[29], "NIDORAN♀");
    assert_eq!(SPECIES_NAMES[32], "NIDORAN♂");
    assert_eq!(SPECIES_NAMES[151], "MEW");
    for (dex, name) in SPECIES_NAMES.iter().enumerate().skip(1) {
        assert!(!name.is_empty(), "dex {dex} has no name");
    }
}

#[test]
fn base_stats_bulbasaur_and_mew() {
    // Type/growth ids from constants/type_constants.asm and
    // constants/pokemon_data_constants.asm: GRASS = $16, POISON = $03,
    // PSYCHIC_TYPE = $18, GROWTH_MEDIUM_SLOW = 3.
    assert_eq!(
        BASE_STATS[1],
        BaseStats {
            hp: 45,
            attack: 49,
            defense: 49,
            speed: 45,
            special: 65,
            type1: 0x16,
            type2: 0x03,
            catch_rate: 45,
            exp_yield: 64,
            growth_rate: 3,
        },
        "Bulbasaur"
    );
    let mew = BASE_STATS[151];
    assert_eq!(
        (mew.hp, mew.attack, mew.defense, mew.speed, mew.special),
        (100, 100, 100, 100, 100),
        "Mew"
    );
    assert_eq!((mew.type1, mew.type2), (0x18, 0x18), "Mew is Psychic");
}

#[test]
fn moves_table() {
    assert_eq!(MOVES.len(), 166);
    assert_eq!(MOVES[0].name, "");
    assert_eq!(MOVES[0].pp, 0);

    let pound = &MOVES[1];
    assert_eq!(pound.name, "POUND");
    assert_eq!(pound.power, 40);
    assert_eq!(pound.type_, 0, "NORMAL");
    assert_eq!(pound.accuracy, 255, "100% accuracy is $FF in the ROM");
    assert_eq!(pound.pp, 35);

    let struggle = &MOVES[165];
    assert_eq!(struggle.name, "STRUGGLE");
    assert_eq!(struggle.power, 50);
    assert_eq!(struggle.pp, 10);

    for (id, m) in MOVES.iter().enumerate().skip(1) {
        assert!(!m.name.is_empty(), "move {id} has no name");
        assert!(m.pp > 0 && m.pp <= 40, "move {id} has bad PP {}", m.pp);
    }
}

#[test]
fn item_names() {
    assert_eq!(ITEM_NAMES[0], "");
    assert_eq!(ITEM_NAMES[1], "MASTER BALL");
    assert_eq!(ITEM_NAMES[4], "POKé BALL");
    assert_eq!(ITEM_NAMES[0x53], "MAX ELIXER", "last regular item");
    assert_eq!(ITEM_NAMES[0x61], "B4F", "last elevator floor pseudo-item");
    assert_eq!(ITEM_NAMES[0x62], "", "glitch item range");
    assert_eq!(ITEM_NAMES[0xC3], "", "glitch item range");
    assert_eq!(ITEM_NAMES[0xC4], "HM01");
    assert_eq!(ITEM_NAMES[0xC8], "HM05");
    assert_eq!(ITEM_NAMES[0xC9], "TM01");
    assert_eq!(ITEM_NAMES[0xFF], "TM55");
}

#[test]
fn type_names() {
    // NUM_TYPES = $1B; ids $09-$13 are unused gaps.
    assert_eq!(TYPE_NAMES.len(), 0x1B);
    assert_eq!(TYPE_NAMES[0x00], "NORMAL");
    assert_eq!(TYPE_NAMES[0x07], "BUG");
    assert_eq!(TYPE_NAMES[0x08], "GHOST");
    for (id, name) in TYPE_NAMES.iter().enumerate().take(0x14).skip(0x09) {
        assert_eq!(*name, "", "type id {id:#04x} is a gap");
    }
    assert_eq!(TYPE_NAMES[0x14], "FIRE");
    assert_eq!(TYPE_NAMES[0x18], "PSYCHIC");
    assert_eq!(TYPE_NAMES[0x1A], "DRAGON");
}

#[test]
fn event_flag_names() {
    // constants/event_constants.asm @ 1e96034 declares 507 named events on
    // sparse bit indexes (the file allocates flags per map with const_next),
    // ending at EVENT_BEAT_ARTICUNO = bit 2522; NUM_EVENTS = $A00 = 2560.
    // The table is indexed by wEventFlags bit, "" for unnamed bits.
    assert_eq!(EVENT_FLAG_NAMES.len(), 0xA00);
    assert_eq!(EVENT_FLAG_NAMES[0], "EVENT_FOLLOWED_OAK_INTO_LAB");
    assert_eq!(EVENT_FLAG_NAMES[1], "");
    assert_eq!(EVENT_FLAG_NAMES[3], "EVENT_HALL_OF_FAME_DEX_RATING");
    assert_eq!(EVENT_FLAG_NAMES[2522], "EVENT_BEAT_ARTICUNO");
    let named = EVENT_FLAG_NAMES.iter().filter(|n| !n.is_empty()).count();
    assert_eq!(named, 507);
    for (bit, name) in EVENT_FLAG_NAMES.iter().enumerate() {
        assert!(
            name.is_empty() || name.starts_with("EVENT_"),
            "bit {bit}: unexpected name {name:?}"
        );
    }
}

#[test]
fn map_names() {
    assert_eq!(MAP_NAMES[0], "PALLET_TOWN");
    assert_eq!(MAP_NAMES[1], "VIRIDIAN_CITY");
    assert_eq!(
        MAP_NAMES[0xF7], "AGATHAS_ROOM",
        "last map id (NUM_MAPS = $F8)"
    );
    for (id, name) in MAP_NAMES.iter().enumerate().skip(0xF8) {
        assert_eq!(*name, "", "map id {id:#04x} is unused");
    }
}
